defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      fullTitleTag: "p"
  -
    scope:
      path: "outcomes/activities"
    values:
      layout: "activity"
      title: Activities
      subTitle: How the outcomes were achieved
      level: 3
gems: [bourbon, neat]